### ISSUE TITLE
IPFS Ignite Roadmap - 2022->2023

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/ipfs-gui#106]
Related to https://github.com/ipfs/ipfs-gui/issues/102

eta: 2023

children:
- [ ] IPFS Desktop and Webui are decoupled from js-ipfs
- [ ] IPFS Desktop startup improvements
- [ ] IPFS Desktop and webui add WebTransport and DAG CAR support
- [ ] Public Gateway Checker metrics and reskin
- [ ] IPFS Desktop and WebUI can keep pace with Kubo feature development
- [ ] IPFS Companion Manifest V3 update
- [ ] IPFS Desktop and Webui can handle display of large CID content
- [ ] Ensure Node.js 18.x support
- [ ] Diagnostic tooling overhaul
- [ ] Peers Map V2 — IPFS Desktop & WebUI
- [ ] IPFS GUI & Tools Metrics standardization
- [ ] IPFS Companion UX Overhaul & Revamp
- [ ] [Starmaps.app](http://starmaps.app/) roadmapping tool V0 Launch
- [ ] [Starmaps.app](http://starmaps.app/) roadmapping tool V1 Launch

**Comment by SgtPooki** [comment]
## 2023-02-16

### Roadmap adjustments and justifications

Note that below is just a proposal, and the changes have not been reflected in the issue description. I will update the description once we have alignment.

#### Remove

* https://github.com/ipfs/ipfs-webui/issues/1965 - I feel like we can make progress on this as we progress on other items. We have already made a huge dent in this with migrating webui to kubo-rpc-client (https://github.com/ipfs/ipfs-webui/pull/2098).
* https://github.com/ipfs/ipfs-gui/issues/115 - This task is tracking some really cool and needed work to ensure devs have a great experience, but this doesn't feel as vital as our already large list of tasks to keep below.
* https://github.com/ipfs/ipfs-desktop/issues/2310 - Not as hard hitting as others, doing it "the right way" requires significant effort
* https://github.com/ipfs/ipfs-gui/issues/110 - public-gateway-checker is our 3rd/4th most used project
* https://github.com/ipfs/ipfs-gui/issues/108 - while improving the startup experience for users is something I think will improve UX significantly, I think we already have enough work and can address this soon after we hit the other important items.
* https://github.com/ipfs/ipfs-gui/issues/116 - building out peers-map as an isolated component could help with https://github.com/ipfs/ipfs-webui/issues/1965 by reducing the breadth of conflicting dependencies in webui, but would increase our team's maintenance burden

#### Keep
* https://github.com/ipfs/ipfs-gui/issues/107 - doing this reduces the scope and complexity of a lot of other issues and allows us to deliver a more consistent experience for our users.
* https://github.com/ipfs/ipfs-gui/issues/109 - CAR files solve a lot of problems for users, and webui+desktop users are not currently benefiting from CAR files.
* https://github.com/ipfs/ipfs-gui/issues/111 - Provide users a stable experience across our ecosystem by facilitating consistent and up-to-date feature support and parity across webui, desktop, and kubo
* https://github.com/ipfs/ipfs-gui/issues/113 - Not displaying any subset of CIDs is a critical bug and reduces the trust of our users.
* https://github.com/ipfs/ipfs-gui/issues/99 - We have to do this by Sep 2023 to ensure we don't end up in a larger mess of tech-debt.
* https://github.com/ipfs/ipfs-gui/issues/117 - done
* https://github.com/ipfs/ipfs-gui/issues/118 - As the project with our largest userbase, revamping the UI for ipfs-companion will provide the largest impact.
* https://github.com/ipfs/ipfs-gui/issues/112 - ipfs-companion has our largest userbase across all our projects, by a large margin, and not doing this will make the extension unusable.
* https://github.com/ipfs/ipfs-gui/issues/119 - done
* https://github.com/ipfs/ipfs-gui/issues/120 - done


---

@whizzzkid, a few questions we ping Steve. 

* do you think the above makes sense for the two of us over 2023? 
* Does this allow us time to help with Helia work? What about general maintenance and existing bugs?
* If you had to add any items to "keep" what would you add that you think we need to do this year?
* If you would remove any one/two items from the "keep" list, which ones would you remove?
* You're already project lead on the companion MV3 work, are there any other tasks you want to take? 
   * Any you want to hand off, or that you really *dont* want to take on?
