### ISSUE TITLE
IPFS Desktop and Webui are decoupled from js-ipfs

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/ipfs-gui#107]
eta: 2023-03-31

description: https://pl-strflt.notion.site/IPFS-Desktop-and-Webui-are-decoupled-from-js-ipfs-2acc399c69994d229307022b23361556

children:

```[tasklist]
### Tasks
- [x] https://github.com/ipfs/kubo/issues/9125
- [ ] https://github.com/ipfs/ipfs-webui/issues/2079
- [ ] https://github.com/ipfs/ipld-explorer-components/issues/359
- [ ] https://github.com/ipfs/ipfs-gui/issues/137
```

**Comment by BigLep** [comment]
Reopening since https://github.com/ipfs/ipfs-gui/issues/137 is open
