### ISSUE TITLE
Ensure Multiformats Are Used Where Possible

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-gui#45]
## Background

I see an opportunity to make people familiar with https://multiformats.io 

Things like CID/multihash are already present in our UIs,  but we still use URL for things like IPFS API or HTTP Gateway in GUI of [ipfs-companion](https://github.com/ipfs/ipfs-companion).

At the same time, `go-ipfs` (commandline daemon) is already printing these addresses as multiaddr:

```
API server listening on /ip4/0.0.0.0/tcp/5001
Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080
```

## Tasks

See if below things exist and create if they do not:

- [x] reusable converter between URL and multiaddr ?
- [ ] HTML5 comes with [built-in validation for URL in `input`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url), we should create a polyfill that does the same for CID and `multiformats` (at least `multihash` and `multiaddr`) and can be used across all GUIs.

Go over our GUI apps and create issues in dedicated repository if  there are places where we could use Multiformat but don't yet:
- [ ] Desktop https://github.com/ipfs-shipyard/ipfs-desktop
- [ ] Companion https://github.com/ipfs-shipyard/ipfs-companion
- [ ] WebUI https://github.com/ipfs-shipyard/ipfs-webui
- should we add anything else here?

**Comment by alanshaw** [comment]
I built this to convert multiaddr to old money: https://github.com/tableflip/multiaddr-to-uri

The comically named `Multiaddr.fromStupidString` will convert a URI to a multiaddr: http://multiformats.github.io/js-multiaddr/#multiaddrfromstupidstring

**Comment by lidel** [comment]
There is also a ready-to-use implementation of multiaddr validation at https://github.com/multiformats/js-mafmt

**Comment by jessicaschilling** [comment]
Closing (stale); please feel free to re-open if necessary. Thanks!
